services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
            - prisma/
        - action: rebuild
          path: package*.json
        - action: rebuild
          path: prisma/schema.prisma